modLoader="javafml"
loaderVersion="[32,)"
license="MIT"
issueTrackerURL="https://github.com/Draylar/wolves-with-armor/issues"

[[mods]]
modId="wolveswitharmor"
version="1.1.0"
displayName="Wolves With Armor"
displayURL="https://github.com/Draylar/wolves-with-armor"
logoFile="icon.png"
authors="Draylar"
contributors="MORTADA KILLER 0"
description='''
Wolves With Armor adds special armor items for wolves (and a few extra utilities) that keep them nice and safe.
'''